# Default values for kube-secrets-init.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of replicas (pods) to launch.
replicaCount: 1

image:
  # -- Name of the image repository to pull the container image from.
  repository: ghcr.io/doitintl/kube-secrets-init

  # -- [Image pull policy](https://kubernetes.io/docs/concepts/containers/images/#updating-images) for updating already existing images on a node.
  pullPolicy: IfNotPresent

  # -- Image tag override for the default value (chart appVersion).
  tag: ""

# -- Log-level for the kube-secrets-init container.
# Valid values are "info", "debug", "warning", "error", "fatal", "panic".
logLevel: info

# -- Reference to one or more secrets to be used when [pulling images](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret) (from private registries).
imagePullSecrets: []

# -- A name in place of the chart name for `app:` labels.
nameOverride: ""

# -- A name to substitute for the full names of resources.
fullnameOverride: ""

# -- One of the supported secret providers:
#   - `google` (Google Cloud Secrets Manager)
#   - `aws` (AWS Secrets Manager and SSM Parameter Store)
provider: ""

defaultImagePullSecret:
  # -- Fallback secret name to use when no image pull secret is found.
  name: ""

  # -- Namespace of the fallback secret name.
  namespace: ""

initContainer:
  image:
    # -- Name of the image repository to pull the init container image from.
    # @default -- `ghcr.io/doitintl/secrets-init` (from CLI defaults)
    repository: ghcr.io/doitintl/secrets-init

    # -- [Image pull policy](https://kubernetes.io/docs/concepts/containers/images/#updating-images) for updating already existing images on a node.
    # @default -- `IfNotPresent` (from CLI defaults)
    pullPolicy: IfNotPresent

    # -- Image tag for the init container.
    # **Note:** it is **strongly** recommended to change the image tag to avoid issues like [this](https://github.com/doitintl/kube-secrets-init/issues/21).
    # @default -- `latest` (from CLI defaults)
    tag: latest

certificate:
  # -- Use jetstack/cert-manager for creating the necessary certificates.
  # This is usually preferred as cert-manager automatically renews certificates.
  # Mutually exclusive with `generate`.
  useCertManager: false

  # -- Generate the necessary certificates during chart install.
  # Mutually exclusive with `useCertManager`.
  generate: true

  # -- The name of the secret to use.
  # If not set and useCertManager or generate is true, a name is generated using the fullname template.
  secretName: ""

serviceAccount:
  # -- Enable service account creation.
  create: true

  # -- Annotations to be added to the service account.
  annotations: {}

  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

rbac:
  # -- Enable the creation of RBAC resources.
  # If disabled, the operator (ie. the person installing the chart) is responsible for creating the necessary resources based on the templates.
  create: true

# -- Annotations to be added to pods.
podAnnotations: {}

# -- Specify a priority class name to set [pod priority](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority).
priorityClassName: ""

podDisruptionBudget:
  # -- Enable a [pod distruption budget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) to help dealing with [disruptions](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/).
  # It is **highly recommended** for webhooks as disruptions can prevent launching new pods.
  enabled: false

  # -- (int/percentage) Number or percentage of pods that must remain available.
  minAvailable:

  # -- (int/percentage) Number or percentage of pods that can be unavailable.
  maxUnavailable:

# -- Pod [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context) for details.
podSecurityContext: {}
  # fsGroup: 2000

# -- Container [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-1) for details.
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

serviceMonitor:
  # -- Enable Prometheus ServiceMonitor.
  enabled: false

  # -- Interval at which metrics should be scraped.
  interval: 30s

# -- Container resource [requests and limits](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#resources) for details.
# @default -- No requests or limits.
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- [Node selector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) configuration.
nodeSelector: {}

# -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) for node taints.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling) for details.
tolerations: []

# -- [Affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity) configuration.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling) for details.
affinity: {}

# -- [Failure policy](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#failure-policy) defines how unrecognized errors and timeout errors from the admission webhook are handled.
# Allowed values are `Ignore` or `Fail`.
failurePolicy: Fail

# -- Allows configuring how long the API server should wait for a webhook to respond before treating the call as a failure.
# See the [documentation](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#timeouts) for details.
timeoutSeconds:

# -- [Namespace selector](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector) for the mutating webhook configuration.
# @default -- Namespaces matching `name=kube-system` selector are excluded.
namespaceSelector:
  matchExpressions:
    - key: name
      operator: NotIn
      values:
        - kube-system
  # matchLabels:
  #   secret-injection: enabled

# -- [Object selector](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-objectselector) for the mutating webhook configuration.
objectSelector: {}
